name: Devops SonarQube Analysis
 
on:
  push:
    branches:
      - main
 
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Run SonarScanner
        run: |
          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=python \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9092 \
            -Dsonar.login=sqp_547b8e507eb3f98c5075dacbc1e7845781bd3b19

  docker:
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
      - name: Build Docker Image
        run: docker build -t samritichopra1909/sam_flask:v1 .
 
      - name: Push Docker Image to Docker Hub
        run: docker push samritichopra1909/sam_flask:v1
