name: Devops SonarQube Analysis
 
on:
  push:
    branches:
      - main
 
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Run SonarScanner
        run: |
         sonar-scanner \
            -Dsonar.projectKey=python \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://13.232.4.242:9092 \
            -Dsonar.login=sqp_547b8e507eb3f98c5075dacbc1e7845781bd3b19
